/*
 * BeamerPoint
 *
 * Author: Abolfazl Mohebbi, PhD
 *         Professor in Mechanical and Biomedical Engineering,
 *         Polytechnique Montreal
 *         abolfazl.mohebbi@polymtl.ca
 */

import { useState } from 'react';
import { SMART_ART, buildSmartArt, type SmartArtKind } from '@beamerpoint/core';

interface Props {
  onCancel(): void;
  onInsert(kind: SmartArtKind, labels: string[]): void;
}

/** A small live preview, built from the real layout function. */
function Preview({ kind, labels }: { kind: SmartArtKind; labels: string[] }): React.ReactElement {
  const W = 110;
  const H = 55;
  const shapes = buildSmartArt(kind, labels, { w: W, h: H });

  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="bp-smart-preview" preserveAspectRatio="xMidYMid meet">
      {shapes.map((s) => {
        const stroke = { stroke: 'currentColor', strokeWidth: 0.4, vectorEffect: 'non-scaling-stroke' as const };
        const fill = s.style.fill === undefined ? 'none' : 'currentColor';
        const op = s.style.fill === undefined ? 1 : 0.16;

        if (s.t === 'rect') {
          return <rect key={s.id} x={s.x} y={s.y} width={s.w} height={s.h} rx={s.rx ?? 0} fill={fill} fillOpacity={op} {...stroke} />;
        }
        if (s.t === 'ellipse') {
          return <ellipse key={s.id} cx={s.cx} cy={s.cy} rx={s.rx} ry={s.ry} fill={fill} fillOpacity={op} {...stroke} />;
        }
        if (s.t === 'path') {
          const d = `M ${s.points.map(([x, y]) => `${x} ${y}`).join(' L ')}${s.closed ? ' Z' : ''}`;
          return <path key={s.id} d={d} fill={fill} fillOpacity={op} {...stroke} />;
        }
        if (s.t === 'arrow' && s.from.kind === 'point' && s.to.kind === 'point') {
          return <line key={s.id} x1={s.from.x} y1={s.from.y} x2={s.to.x} y2={s.to.y} {...stroke} />;
        }
        return null;
      })}
    </svg>
  );
}

/**
 * Pick a layout and give it labels.
 *
 * The preview is generated by the same function that builds the real diagram, so what
 * is shown is what gets inserted — no separate artwork to fall out of date.
 */
export function SmartArtPicker({ onCancel, onInsert }: Props): React.ReactElement {
  const [kind, setKind] = useState<SmartArtKind>('process');
  const [text, setText] = useState(SMART_ART[0]!.sample.join('\n'));

  const spec = SMART_ART.find((s) => s.kind === kind)!;
  const labels = text.split('\n').map((l) => l.trim()).filter((l) => l !== '');
  const tooMany = labels.length > spec.max;

  const choose = (next: SmartArtKind): void => {
    const nextSpec = SMART_ART.find((s) => s.kind === next)!;
    // Carry the user's own labels across; only reset when they have not typed any.
    const current = text.split('\n').map((l) => l.trim()).filter((l) => l !== '');
    const untouched = SMART_ART.some((s) => s.sample.join('\n') === text);
    setKind(next);
    if (untouched || current.length === 0) setText(nextSpec.sample.join('\n'));
  };

  return (
    <div className="bp-modal-backdrop" onClick={onCancel}>
      <div className="bp-modal bp-smart-modal" onClick={(e) => e.stopPropagation()}>
        <h3>Insert a diagram layout</h3>

        <div className="bp-smart-grid">
          {SMART_ART.map((s) => (
            <button
              key={s.kind}
              className={`bp-smart-card${kind === s.kind ? ' is-active' : ''}`}
              onClick={() => choose(s.kind)}
              title={s.hint}
            >
              <Preview kind={s.kind} labels={s.sample} />
              <span>{s.label}</span>
            </button>
          ))}
        </div>

        <div className="bp-smart-edit">
          <label className="bp-field">
            <span>Labels — one per line. {spec.hint}</span>
            <textarea
              rows={5}
              value={text}
              onChange={(e) => setText(e.target.value)}
              spellCheck={false}
            />
          </label>
          <div className="bp-smart-live">
            <Preview kind={kind} labels={labels} />
          </div>
        </div>

        {tooMany && (
          <p className="bp-hint bp-hint-warn">
            {spec.label} uses at most {spec.max} labels; the rest will be ignored.
          </p>
        )}
        {labels.length < spec.min && (
          <p className="bp-hint bp-hint-warn">
            {spec.label} needs at least {spec.min} labels — the sample will be used to
            fill the gaps.
          </p>
        )}

        <div className="bp-modal-actions">
          <button onClick={onCancel}>Cancel</button>
          <button className="bp-primary" onClick={() => onInsert(kind, labels)}>
            Insert
          </button>
        </div>
        <p className="bp-muted bp-modal-note">
          Inserted as ordinary shapes, so you can move, restyle and delete any part of it.
        </p>
      </div>
    </div>
  );
}
