/**
 * Beamer's real colours, MEASURED — do not hand-edit.
 *
 * Generated by the procedure in `tools/theme-colours.md`: each theme is compiled with
 * `\usebeamercolor` + `\extractcolorspec` + `\typeout`, so these are the values beamer
 * itself resolves, not an approximation of them.
 *
 * This replaced a derivation that mixed every colour from a single hand-written
 * `structure` hex per theme. That was wrong in ways nobody could see without compiling:
 * AnnArbor's frame title is Michigan maize `#fff200` and the canvas drew it navy;
 * CambridgeUS's is light grey `#f2f2f2` and the canvas drew it maroon; Madrid's footline
 * ran light-dark-light where beamer runs it dark-to-light.
 *
 * Only the four themes that cannot compile here (Arguelles, CleanEasy, focus, trigon —
 * all missing font packages) have no entry, and those fall back to the derivation.
 *
 * FORMAT. One string per theme. Fields in `MEASURED_FIELDS` order, separated by a space;
 * within a field, `fg,bg` as six-digit hex without the `#`, either side empty when beamer
 * defines no such colour. Encoded rather than spelled out because this is generated data:
 * 35 themes x 24 fields x 2 colours is 1680 values, and a readable object literal of that
 * is four times the size for no benefit at a call site that never reads it directly.
 */

export const MEASURED_FIELDS = [
  'normalText', 'structure', 'alertedText', 'frametitle', 'title', 'subtitle',
  'author', 'institute', 'date', 'blockTitle', 'blockBody', 'blockTitleAlerted',
  'blockBodyAlerted', 'blockTitleExample', 'blockBodyExample', 'palettePrimary',
  'paletteSecondary', 'paletteTertiary', 'sectionInHeadFoot', 'authorInHeadFoot',
  'titleInHeadFoot', 'dateInHeadFoot', 'backgroundCanvas', 'sidebar',
] as const;

export type MeasuredField = (typeof MEASURED_FIELDS)[number];

/** A foreground/background pair. Either may be absent. */
export interface MeasuredPair {
  fg?: string;
  bg?: string;
}

export type MeasuredTheme = Partial<Record<MeasuredField, MeasuredPair>>;

/* eslint-disable max-len */
const RAW: Readonly<Record<string, string>> = {
  AnnArbor: '000000,ffffff 3333b3,ffffff 3333a3,ffffff 3333b3,fff200 3333b3,ffec00 3333b3,ffec00 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff 3333a3,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 00007a,ffec00 00008f,ffcc00 ffbf00,0000a3 ffbf00,0000a3 ffbf00,0000a3 00008f,ffcc00 00007a,ffec00 000000,ffffff 0000cc,ff9f40',
  Antibes: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,3333b3 ffffff,000000 ffffff,262686 000000,ffffff 000000,3333b3',
  Bergen: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ff4040,bf0000 000000,f9e6e6 80ff80,006000 000000,e6efe6 3333b3,ffffff 262686,ffffff 191959,ffffff 191959,ffffff 3333b3,ffffff 000000,ffffff 262686,ffffff 000000,ffffff ffffff,262686',
  Berkeley: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,3333b3 ffffff,000000 ffffff,262686 000000,ffffff 000000,3333b3',
  Berlin: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,262686 ffffff,191959 ffffff,262686 000000,ffffff 000000,3333b3',
  Boadilla: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,d6d6f0 000000,ebebf7 ff0000,ffcccc 000000,ffe6e6 008000,cce6cc 000000,e6f2e6 000000,adade0 ffffff,8585d1 ffffff,4747ba ffffff,4747ba ffffff,4747ba ffffff,8585d1 000000,adade0 000000,ffffff 000000,3333b3',
  CambridgeUS: '000000,ffffff 3333b3,ffffff bd1a1a,ffffff cc0000,f2f2f2 cc0000,ffffff cc0000,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff bd1a1a,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 7a0000,d9d9d9 8f0000,ececec f2f2f2,a30000 f2f2f2,a30000 f2f2f2,a30000 8f0000,ececec 7a0000,d9d9d9 000000,ffffff cc0000,ececec',
  Copenhagen: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,000000 ffffff,000000 ffffff,3333b3 ffffff,262686 000000,ffffff 000000,3333b3',
  Cuerna: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff ffffff,ffffff ffffff,ffffff ffffff,ffffff ffffff,002b36 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 3333b3,ffffff 262686,ffffff 191959,ffffff 191959,ffffff 3333b3,ffffff 000000,ffffff 262686,ffffff 000000,ffffff 000000,ffffff',
  Darmstadt: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,000000 ffffff,3333b3 ffffff,000000 ffffff,262686 000000,ffffff 000000,3333b3',
  Dresden: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,262686 ffffff,191959 ffffff,262686 000000,ffffff 000000,3333b3',
  EastLansing: '000000,ffffff 3333b3,ffffff 33855c,ffffff 3333b3,e6f0eb 3333b3,d9e8e0 3333b3,d9e8e0 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff 33855c,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 003d1f,d9e8e0 004724,99c2ad 80b399,005229 80b399,005229 80b399,005229 004724,99c2ad 003d1f,d9e8e0 000000,ffffff 006633,408c66',
  Frankfurt: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,000000 ffffff,3333b3 ffffff,000000 ffffff,262686 000000,ffffff 000000,3333b3',
  Goettingen: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 3333b3,ffffff 262686,ffffff 191959,ffffff 191959,ffffff 3333b3,ffffff 000000,ffffff 262686,ffffff 000000,ffffff 000000,ffffff',
  Hannover: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 000000,d6d6f0 000000,ccccec 000000,c2c2e8 000000,c2c2e8 000000,d6d6f0 000000,b8b8e4 000000,ccccec 000000,ffffff 000000,d6d6f0',
  Ilmenau: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,262686 ffffff,191959 ffffff,262686 000000,ffffff 000000,3333b3',
  JuanLesPins: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,3333b3 ffffff,000000 ffffff,262686 000000,ffffff 000000,3333b3',
  Luebeck: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,000000 ffffff,000000 ffffff,3333b3 ffffff,262686 000000,ffffff 000000,3333b3',
  Madrid: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,191959 ffffff,262686 ffffff,3333b3 000000,ffffff 000000,3333b3',
  Malmoe: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,000000 ffffff,000000 ffffff,3333b3 ffffff,262686 000000,ffffff 000000,3333b3',
  Marburg: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,3333b3 ffffff,000000 ffffff,262686 000000,ffffff ffffff,3333b3',
  Montpellier: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 3333b3,ffffff 262686,ffffff 191959,ffffff 191959,ffffff 3333b3,ffffff 000000,ffffff 262686,ffffff 000000,ffffff 000000,ffffff',
  Nord: 'd8dee9,ffffff 8fbcbb,ffffff bf616a,ffffff a3be8c,ffffff a3be8c,ffffff 81a1c1,ffffff d8dee9,ffffff d8dee9,ffffff d8dee9,ffffff a3be8c,626875 8fbcbb,6f806f bf616a,626875 d8dee9,7d525e 88c0d0,626875 d8dee9,618191 8fbcbb,ffffff 6b8d8c,ffffff 485e5e,ffffff 8fbcbb,3b4252 8fbcbb,ffffff 000000,ffffff 6b8d8c,ffffff d8dee9,3b4252 d8dee9,ffffff',
  PaloAlto: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,3333b3 ffffff,000000 ffffff,262686 000000,ffffff 000000,3333b3',
  Pittsburgh: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 3333b3,ffffff 262686,ffffff 191959,ffffff 191959,ffffff 3333b3,ffffff 000000,ffffff 262686,ffffff 000000,ffffff 000000,ffffff',
  Rochester: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,191959 ffffff,3333b3 ffffff,000000 ffffff,262686 000000,ffffff 000000,3333b3',
  SimpleDarkBlue: '000000,ffffff 0d2659,ffffff ff0000,ffffff ffffff,0d2659 ffffff,0d2659 ffffff,0d2659 000000,ffffff 000000,ffffff 000000,ffffff ffffff,045073 000000,ebebf7 ffffff,ec5858 000000,f7ebeb ffffff,5eb3a8 000000,ebf7eb 0d2659,ffffff 0a1d43,ffffff 06132d,ffffff 06132d,ffffff 0d2659,ffffff 000000,ffffff 0a1d43,ffffff 000000,ffffff 000000,ffffff',
  SimplePlus: '000000,ffffff 0d2659,ffffff ff0000,ffffff 0d2659,ffffff 0d2659,ffffff 0d2659,ffffff 000000,ffffff 000000,ffffff 000000,ffffff ffffff,045073 000000,ebebf7 ffffff,ec5858 000000,f7ebeb ffffff,5eb3a8 000000,ebf7eb 0d2659,ffffff 0a1d43,ffffff 06132d,ffffff 06132d,ffffff 0d2659,ffffff 000000,ffffff 0a1d43,ffffff 000000,ffffff 000000,ffffff',
  Singapore: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 3333b3,ffffff 262686,ffffff 191959,ffffff 191959,ccccec 262686,ffffff 191959,ccccec 262686,ffffff 000000,ffffff 000000,ffffff',
  Szeged: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 3333b3,ffffff 262686,ffffff 191959,ffffff 191959,ffffff 262686,ffffff 191959,ffffff 262686,ffffff 000000,ffffff 000000,ffffff',
  Warsaw: '000000,ffffff 3333b3,ffffff ff0000,ffffff ffffff,3333b3 ffffff,3333b3 ffffff,3333b3 000000,ffffff 000000,ffffff 000000,ffffff ffffff,262686 000000,e9e9f3 ffffff,bf0000 000000,f9e6e6 ffffff,006000 000000,e6efe6 ffffff,3333b3 ffffff,262686 ffffff,191959 ffffff,000000 ffffff,000000 ffffff,3333b3 ffffff,262686 000000,ffffff 000000,3333b3',
  boxes: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 3333b3,ffffff 262686,ffffff 191959,ffffff 191959,ffffff 3333b3,ffffff 000000,ffffff 262686,ffffff 000000,ffffff 000000,ffffff',
  default: '000000,ffffff 3333b3,ffffff ff0000,ffffff 3333b3,ffffff 3333b3,ffffff 3333b3,ffffff 000000,ffffff 000000,ffffff 000000,ffffff 3333b3,ffffff 000000,ffffff ff0000,ffffff 000000,ffffff 008000,ffffff 000000,ffffff 3333b3,ffffff 262686,ffffff 191959,ffffff 191959,ffffff 3333b3,ffffff 000000,ffffff 262686,ffffff 000000,ffffff 000000,ffffff',
  metropolis: '23373b,fafafa 23373b,fafafa eb811b,fafafa fafafa,23373b 23373b,fafafa 23373b,fafafa 23373b,fafafa 23373b,fafafa 23373b,fafafa 23373b,fafafa 23373b,fafafa eb811b,fafafa 23373b,fafafa 14b03d,fafafa 23373b,fafafa fafafa,23373b 1a292c,fafafa 111c1e,fafafa 111c1e,fafafa fafafa,23373b 000000,fafafa 1a292c,fafafa 23373b,fafafa 23373b,fafafa',
  moloch: '23373b,fafafa 23373b,fafafa eb811b,fafafa fafafa,23373b 23373b,fafafa 23373b,fafafa 23373b,fafafa 4e5e61,fafafa 23373b,fafafa 23373b,fafafa 23373b,fafafa eb811b,fafafa 23373b,fafafa 008080,fafafa 23373b,fafafa 23373b,23373b 1a292c,fafafa 111c1e,fafafa 111c1e,fafafa 23373b,23373b 000000,fafafa 1a292c,fafafa 23373b,fafafa 23373b,fafafa',
};
/* eslint-enable max-len */

function decode(row: string): MeasuredTheme {
  const out: MeasuredTheme = {};
  const parts = row.split(' ');
  MEASURED_FIELDS.forEach((field, i) => {
    const raw = parts[i];
    if (raw === undefined) return;
    const [fg, bg] = raw.split(',');
    const pair: MeasuredPair = {};
    if (fg) pair.fg = `#${fg}`;
    if (bg) pair.bg = `#${bg}`;
    if (pair.fg !== undefined || pair.bg !== undefined) out[field] = pair;
  });
  return out;
}

/** Decoded once at load; 35 small objects, so eager is simpler than lazy. */
export const MEASURED: Readonly<Record<string, MeasuredTheme>> = Object.fromEntries(
  Object.entries(RAW).map(([theme, row]) => [theme, decode(row)]),
);

/** True when this theme's colours came from the engine rather than from derivation. */
export function hasMeasuredColors(theme: string): boolean {
  return theme in MEASURED;
}
