import type { Mm } from '../model/types.js';

/**
 * Where each theme's title page puts its lines — MEASURED, do not hand-edit.
 *
 * Generated by the procedure in `tools/theme-colours.md`: a `\titlepage` is compiled per
 * theme with known sample text, and each line's baseline, font size and horizontal
 * anchor come out of the PDF's text layer.
 *
 * The canvas used to draw `\titlepage` as a grey box containing the literal characters
 * `\titlepage`, which resembled the compiled slide not at all. Twenty-eight of the 35
 * themes do share beamer's default layout, but the ones that do not are not close:
 * metropolis and moloch are left-aligned at the text margin and reorder the credits,
 * Nord sets its title at 24.8pt and runs author and institute onto one line, Cuerna puts
 * the author at the FOOT of the page, and the sidebar themes centre on their text area
 * rather than on the page.
 *
 * FORMAT. `align|anchor|line|line|...`, where `align` is `c` or `l`, `anchor` is the
 * block's centre in millimetres when centred and its left edge when not, and each line
 * is `baselineMm:sizePt:field[+field...]`. Fields sharing a baseline are set on one line
 * by beamer and are rendered on one line here.
 *
 * NOT captured: decorations with no field of their own — Bergen's "Who? / From? / When?"
 * labels and Nord's "by" and "on". They are part of those themes' title pages and the
 * canvas simply omits them.
 */

export type TitleField = 'title' | 'subtitle' | 'author' | 'institute' | 'date';

export interface TitleLine {
  /** Millimetres from the top of the page to this line's baseline. */
  baselineMm: Mm;
  /** Font size in points, as the engine set it. */
  sizePt: number;
  /** The fields on this line, in the order beamer sets them. */
  fields: readonly TitleField[];
}

export interface TitleLayout {
  align: 'center' | 'left';
  /** The block's centre when centred, its left edge when left-aligned. */
  anchorMm: Mm;
  lines: readonly TitleLine[];
}

const RAW: Readonly<Record<string, string>> = {
  AnnArbor: 'c|80.0|26.0:14.3:title|32.0:10.9:subtitle|46.1:10.9:author|54.0:8.0:institute|63.2:10.9:date',
  Antibes: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Bergen: 'c|61.0|21.5:14.3:title|26.3:10.9:subtitle|48.5:10.9:author|56.5:8.0:institute|64.4:10.9:date',
  Berkeley: 'c|87.9|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Berlin: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Boadilla: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  boxes: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  CambridgeUS: 'c|80.0|26.0:14.3:title|32.0:10.9:subtitle|46.1:10.9:author|54.0:8.0:institute|63.2:10.9:date',
  Copenhagen: 'c|80.0|26.3:14.3:title|32.3:10.9:subtitle|45.7:10.9:author|53.6:8.0:institute|62.8:10.9:date',
  Cuerna: 'l|21.5|19.6:20.7:title|31.1:12.0:date|76.0:12.0:author|81.8:6.0:institute',
  Darmstadt: 'c|80.0|26.0:14.3:title|32.0:10.9:subtitle|46.1:10.9:author|54.0:8.0:institute|63.2:10.9:date',
  default: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Dresden: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  EastLansing: 'c|80.0|26.3:14.3:title|32.3:10.9:subtitle|45.7:10.9:author|53.6:8.0:institute|62.8:10.9:date',
  Frankfurt: 'c|80.0|26.0:14.3:title|32.0:10.9:subtitle|46.1:10.9:author|54.0:8.0:institute|63.2:10.9:date',
  Goettingen: 'c|70.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Hannover: 'c|87.9|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Ilmenau: 'c|80.0|26.3:14.3:title|32.3:10.9:subtitle|45.7:10.9:author|53.6:8.0:institute|62.8:10.9:date',
  JuanLesPins: 'c|80.0|26.0:14.3:title|32.0:10.9:subtitle|46.1:10.9:author|54.0:8.0:institute|63.2:10.9:date',
  Luebeck: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Madrid: 'c|80.0|26.0:14.3:title|32.0:10.9:subtitle|46.1:10.9:author|54.0:8.0:institute|63.2:10.9:date',
  Malmoe: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Marburg: 'c|70.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  metropolis: 'l|10.0|25.9:14.3:title|34.1:12.0:subtitle|53.6:10.0:author|59.3:10.0:date|66.1:8.0:institute',
  moloch: 'l|10.0|37.6:14.3:title|43.8:12.0:subtitle|55.8:10.0:author|60.9:8.0:institute|68.0:10.0:date',
  Montpellier: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Nord: 'l|10.0|28.8:24.8:title|37.5:14.3:subtitle|50.0:10.9:author+institute|55.1:10.9:date',
  PaloAlto: 'c|87.9|26.0:14.3:title|32.0:10.9:subtitle|46.1:10.9:author|54.0:8.0:institute|63.2:10.9:date',
  Pittsburgh: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Rochester: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  SimpleDarkBlue: 'c|80.0|38.7:17.2:title|45.0:10.9:subtitle|58.1:12.0:author|62.2:8.0:institute|70.6:8.0:date',
  SimplePlus: 'c|80.0|37.5:17.2:title|43.9:10.9:subtitle|55.5:12.0:author|59.6:8.0:institute|68.0:8.0:date',
  Singapore: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Szeged: 'c|80.0|25.4:14.3:title|31.5:10.9:subtitle|43.9:10.9:author|51.9:8.0:institute|61.1:10.9:date',
  Warsaw: 'c|80.0|26.0:14.3:title|32.0:10.9:subtitle|46.1:10.9:author|54.0:8.0:institute|63.2:10.9:date',
};

function decode(row: string): TitleLayout {
  const [align, anchor, ...lines] = row.split('|');
  return {
    align: align === 'l' ? 'left' : 'center',
    anchorMm: Number(anchor),
    lines: lines.map((l) => {
      const [baseline, size, fields] = l.split(':');
      return {
        baselineMm: Number(baseline),
        sizePt: Number(size),
        fields: (fields ?? '').split('+') as TitleField[],
      };
    }),
  };
}

export const TITLE_LAYOUTS: Readonly<Record<string, TitleLayout>> =
  Object.fromEntries(Object.entries(RAW).map(([k, v]) => [k, decode(v)]));

/**
 * Beamer's own layout, used for a theme that was never measured.
 *
 * Twenty-eight of the 35 measured themes agree with it to within a millimetre, so it is
 * the right thing to fall back to.
 */
export const DEFAULT_TITLE_LAYOUT: TitleLayout = TITLE_LAYOUTS['default']!;

export function titleLayoutFor(theme: string): TitleLayout {
  return TITLE_LAYOUTS[theme] ?? DEFAULT_TITLE_LAYOUT;
}
